### ISSUE TITLE
Tidy5eSheet not working correctly with Skill Customization

### ISSUE THREAD

**Issue by kleelue** [schultzcole/FVTT-Skill-Customization-5e#1]
Hi there,

I'm using Tidy5eSheet in conjunction with Skill Customization for D&D5e and there are Proficiencies missing on the sheet. For comparison here the standard sheet:
![image](https://user-images.githubusercontent.com/66916262/84599063-8f7a9600-ae6f-11ea-9a27-a2377094c1d5.png)
and then your sheet:
![image](https://user-images.githubusercontent.com/66916262/84599078-a6b98380-ae6f-11ea-8675-43927c17b47e.png)
Dark and Light Theme have the problem in common. And as you can see - Stealth for example is missing. If I deactivate Skill customization, Stealth shows up on the TidySheet. So something is not quite right. Please have a look into it. Until then, I will use the standard sheets.

**Comment by schultzcole** [comment]
Thanks for the report! I'll look into it and hopefully have an update out soon

**Comment by schultzcole** [comment]
This issue should be resolved in 1.2.1. Thanks for the report!
