### ISSUE TITLE
Feature: Add custom Skills

### ISSUE THREAD

**Issue by Jmwhite45** [schultzcole/FVTT-Skill-Customization-5e#10]
The ability to add new skills would be a nice feature. 

My idea would be to add a + at the bottom of the skills where you can add a skill, name it, and set the ability score it uses.

**Comment by schultzcole** [comment]
For this I would recommend using D&D5e Extender: https://github.com/schultzcole/FVTT-DND5e-Extender

Adding custom skills is a relatively involved process so I'd like to keep that isolated to the dnd5e extender module
