### ISSUE TITLE
[Feature Request] Add custom skills/ability to the character sheet

### ISSUE THREAD

**Issue by p4535992** [schultzcole/FVTT-Skill-Customization-5e#12]
It is possible to add the ability to add skills with customized labels, setting the mod to use (DEX, STR, etc.)?

For example the "Swimming" skill to understand with some roll if someone is drowning or not.

**Comment by schultzcole** [comment]
Adding new custom skills is coming in a future dnd5e update (currently 1.7 I think), so I'm waiting for that release rather than adding my own implementation.

**Comment by p4535992** [comment]
gotcha
