### ISSUE TITLE
Odd alignment when using Tidy5e

### ISSUE THREAD

**Issue by EllatharTheHalfling** [schultzcole/FVTT-Skill-Customization-5e#13]
Writing this mostly because there is a small issue with alignment with Tidy5e when using 3.0.0, currently on Foundry v9.

3.0.0 + Tidy5e:
![image](https://user-images.githubusercontent.com/67206562/171495389-5998446c-9cbd-4f87-a5d5-22881799983f.png)

3.0.0 Standalone:
![image](https://user-images.githubusercontent.com/67206562/171496497-acf43bde-46fd-41ed-ba5b-a42a96ba7f86.png)

2.3.0 (used to test whether or not the alignment issue was version specific) + Tidy5e:
![image](https://user-images.githubusercontent.com/67206562/171495598-0ded89e8-28fc-4090-974f-e512aa39f634.png)

I'll try to solve this myself within the CSS, however I'm not sure when I'll have the time to poke around with that and felt it more efficient to bring this up here just in case you might happen to get to it first.

**Comment by schultzcole** [comment]
Ah, thanks for reporting this. I'll check it later tonight.

**Comment by schultzcole** [comment]
This should be resolved in skill customization [3.0.1](https://github.com/schultzcole/FVTT-Skill-Customization-5e/releases/tag/3.0.1)
