### ISSUE TITLE
Support Better Rolls

### ISSUE THREAD

**Issue by MrPrimate** [schultzcole/FVTT-Skill-Customization-5e#2]
I like using Better Rolls, would you be able to support it?

**Comment by schultzcole** [comment]
In my testing, Better Rolls works correctly with this mod. Is there a particular set of settings for which it doesn't work correctly?

**Comment by MrPrimate** [comment]
After some further testing I think my problem was with better roles, there are some changes in v0.93 which change where global modifiers are added.
