### ISSUE TITLE
Feature Request: Ability to add new custom skills

### ISSUE THREAD

**Issue by Norc** [schultzcole/FVTT-Skill-Customization-5e#3]
@Will.I.Am#7000 requested the ability to add custom skills:

https://discord.com/channels/170995199584108546/722559135371231352/725331001785450547

He was not particular if it was global or per-character, and envisioned using it for tool proficiencies. There could be other uses also, as this is a pretty flexible concept.

**Comment by alvileiz** [comment]
It'll will awesome for Adventures in Middle Earth or Wands & Wizards that add new skills

**Comment by schultzcole** [comment]
Sorry, I should have closed this earlier. I am sorry to say that this is not in the plans for Skill Customization.
