### ISSUE TITLE
version.0.7.5

### ISSUE THREAD

**Issue by HippyCraig** [schultzcole/FVTT-Skill-Customization-5e#5]
When enabling this in version.0.7.5 I get this from the console

Foundry VTT | Error thrown in hooked function 
_call	@	foundry.js:2428
callAll	@	foundry.js:2386
callOriginalFunction	@	Patches.js:59
(anonymous)	@	Debug.js:33
_getControlButtons	@	foundry.js:20034
SceneControls	@	foundry.js:19487
initializeUI	@	foundry.js:6563
setupGame	@	foundry.js:6474
async function (async)		
setupGame	@	foundry.js:6468
_initializeGameView	@	foundry.js:7227
initialize	@	foundry.js:6404
async function (async)		
initialize	@	foundry.js:6396
window.addEventListener.once	@	foundry.js:7359
async function (async)		
window.addEventListener.once	@	foundry.js:7358
foundry.js:2429 TypeError: Cannot read property 'simplefog' of null
    at controls.js:23
    at Function._call (foundry.js:2426)
    at Function.callAll [as __furnace_original_callAll] (foundry.js:2386)
    at Function.callOriginalFunction (Patches.js:59)
    at Function.<anonymous> (Debug.js:33)
    at SceneControls._getControlButtons (foundry.js:20034)
    at new SceneControls (foundry.js:19487)
    at Game.initializeUI (foundry.js:6563)
    at Game.setupGame (foundry.js:6474)
    at async Game._initializeGameView (foundry.js:7227)
_call	@	foundry.js:2429
callAll	@	foundry.js:2386
callOriginalFunction	@	Patches.js:59
(anonymous)	@	Debug.js:33
_getControlButtons	@	foundry.js:20034
SceneControls	@	foundry.js:19487
initializeUI	@	foundry.js:6563
setupGame	@	foundry.js:6474
async function (async)		
setupGame	@	foundry.js:6468
_initializeGameView	@	foundry.js:7227
initialize	@	foundry.js:6404
async function (async)		
initialize	@	foundry.js:6396
window.addEventListener.once	@	foundry.js:7359
async function (async)		
window.addEventListener.once	@	foundry.js:7358
foundry.js:2428 Foundry VTT | Error thrown in hooked function 
_call	@	foundry.js:2428
call	@	foundry.js:2411
callOriginalFunction	@	Patches.js:59
(anonymous)	@	Debug.js:42
_render	@	foundry.js:4472
async function (async)		
_render	@	foundry.js:4434
render	@	foundry.js:4404
initializeUI	@	foundry.js:6574
setupGame	@	foundry.js:6474
async function (async)		
setupGame	@	foundry.js:6468
_initializeGameView	@	foundry.js:7227
initialize	@	foundry.js:6404
async function (async)		
initialize	@	foundry.js:6396
window.addEventListener.once	@	foundry.js:7359
async function (async)		
window.addEventListener.once	@	foundry.js:7358
foundry.js:2429 TypeError: Cannot read property 'simplefog' of null
    at controls.js:117
    at Function._call (foundry.js:2426)
    at Function.call [as __furnace_original_call] (foundry.js:2411)
    at Function.callOriginalFunction (Patches.js:59)
    at Function.<anonymous> (Debug.js:42)
    at SceneControls._render (foundry.js:4472)
_call	@	foundry.js:2429
call	@	foundry.js:2411
callOriginalFunction	@	Patches.js:59
(anonymous)	@	Debug.js:42
_render	@	foundry.js:4472
async function (async)		
_render	@	foundry.js:4434
render	@	foundry.js:4404
initializeUI	@	foundry.js:6574
setupGame	@	foundry.js:6474
async function (async)		
setupGame	@	foundry.js:6468
_initializeGameView	@	foundry.js:7227
initialize	@	foundry.js:6404
async function (async)		
initialize	@	foundry.js:6396
window.addEventListener.once	@	foundry.js:7359
async function (async)		
window.addEventListener.once	@	foundry.js:7358

**Comment by schultzcole** [comment]
These error messages appear to be coming from the simple fog module, not Skill Customization. Can you disable all other modules and verify whether Skill Customization is actually the culprit here?

**Comment by HippyCraig** [comment]
It is Im sorry I clicked the wrong link from within FVTT.  Please disregard
