### ISSUE TITLE
Dice bonuses don't work with BetterRollsFor5e

### ISSUE THREAD

**Issue by cs96and** [schultzcole/FVTT-Skill-Customization-5e#6]
When BetterRollsFor5e is enabled, dice bonuses to skills don't work (flat bonuses still work though).

If I disable Better Rolls, then the dice bonuses start working.

Foundry 0.7.7
Better Rolls 1.2.0
Skill Customizations 2.1.0

**Comment by schultzcole** [comment]
Hi @cs96and, sorry for not responding sooner. This is a known issue and unfortunately it is up to Better Rolls to add support for dice bonuses, or at least it would require changes on both sides. Currently as far as I know, Better Rolls just uses the flat pre-calculated total bonus, which of course does not include the the dice bonus provided by skill customization.

**Comment by cs96and** [comment]
I've switched to Quick Rolls now, so this is no longer an issue
