### ISSUE TITLE
Return the result of rollSkill() to maintain compatibility

### ISSUE THREAD

**Issue by CarlosFdez** [schultzcole/FVTT-Skill-Customization-5e#7]
The rollSkill() function in the 5e system actually returns a roll object(), which is used by modules as Midi (allegedly) and will be used by BetterRolls in a later version. However the rollSkill() overwrite you do does not return anything. If you add a return statement to https://github.com/schultzcole/FVTT-Skill-Customization-5e/blob/master/skl-customization.js#L60 it should (didn't test it) maintain compatibility by ensuring the type signature is compatible with vanilla 5e.

I started looking into it after @Sky-Captain-13 asked about compatibility with dice roll modifiers (like 1d4) in the discord.

**Comment by schultzcole** [comment]
Nice catch, I'll release an update with that change in a bit.

**Comment by schultzcole** [comment]
Added in 2.2.0
