### ISSUE TITLE
Tool Proficiency and Skill Customization module conflict

### ISSUE THREAD

**Issue by jsmith2500** [schultzcole/FVTT-Skill-Customization-5e#9]
When ever I have libWrapper enabled it shows that there is a conflict between “Tools Proficiencies for DnD 5e” and “Skill Customization for D&D 5e”. If both are enabled I can not open a character sheet from the menu or a token. If I disable one of them the character sheet opens fine. Posting this on the other module site.
![image](https://user-images.githubusercontent.com/81322327/112376091-07ed6d80-8cb2-11eb-8406-4c25b18a2fbb.png)

**Comment by schultzcole** [comment]
Yeah, this is an issue on the tool proficiencies side. It appears to produce errors even when it is the only module enabled. The author will need to resolve the problems with their module that are causing problems. Once they've resolved those issues if the problem with sheets not opening continues to happen feel free to re-open this and I'll investigate again.
